
agent:
  enabled: true
  replicas: 1
  image:
    repository: ghcr.io/your-org/tennis-agent
    tag: latest
  mode: SIM
  logLevel: INFO
  eventTypeIds: "2"
  marketTypes: "MATCH_ODDS"
  edgeThreshold: 0.05
  maxRiskPct: 0.01
  bankroll: 1000.0
  minOdds: 1.01
  maxOdds: 1000.0
  inplayOnly: false
  predictionApiUrl: ""
  metricsPort: 9100
  secretsRef: tennis-agent-secrets
  certSecretRef: betfair-cert-secret
  dailyStopLoss: 100.0
  dailyTakeProfit: 1000.0
  dailyMaxBets: 200
  serviceMonitor:
    enabled: true
    release: prometheus
  grafanaDashboard:
    enabled: true
  alerts:
    enabled: true
    release: prometheus
    dailyStopLoss: 100
    maxPendingExposure: 1000

ui:
  enabled: true
  replicas: 1
  secretsRef: tennis-ui-secrets
  frontend:
    image:
      repository: ghcr.io/your-org/tennis-ui
      tag: latest
  gateway:
    image:
      repository: ghcr.io/your-org/tennis-ui-gateway
      tag: latest
    promUrl: "http://prometheus-k8s.monitoring:9090"
    oidc:
      issuer: ""    # e.g., https://dev-abc123.us.auth0.com or https://keycloak.example.com/realms/tennis
      audience: ""  # API audience expected in access_token (Auth0) or client_id (Keycloak)
      jwksUrl: ""   # optional override of JWKS URL
  oidc:
    provider: "auth0" # or "keycloak"
    issuer: ""        # same as gateway.oidc.issuer
  ingress:
    enabled: false
    className: nginx
    host: mcp.example.com
    tlsSecretName: mcp-tls
