
{{- if .Values.agent.enabled }}
apiVersion: v1
kind: Secret
metadata: { name: {{ .Values.agent.secretsRef }} }
type: Opaque
stringData:
  bf_username: "CHANGE_ME"
  bf_password: "CHANGE_ME"
  bf_app_key: "CHANGE_ME"
  prediction_api_key: ""
---
apiVersion: v1
kind: Secret
metadata: { name: {{ .Values.agent.certSecretRef }} }
type: Opaque
data:
  client-2048.crt: ""
  client-2048.key: ""
{{- end }}
