routes:
  enabled: true
  predictionApiHost: "prediction-api.apps.prod.example.com"

minio:
  enabled: true
  persistence:
    enabled: true
    size: "1Ti"
    storageClass: "fast-ssd"
  routeHostConsole: "minio-console.apps.prod.example.com"
  routeHostApi: "minio-api.apps.prod.example.com"

mlflow:
  enabled: true
  backendUri: "postgresql://mlflow:***@pg-ml-rw.tnns-prod.svc:5432/mlflow"
  s3Endpoint: "http://minio.tnns-prod.svc:9000"
  s3AccessKeySecret: "tnns-s3"
  s3SecretKeySecret: "tnns-s3"
  routeHost: "mlflow.apps.prod.example.com"

airflow:
  enabled: false

kafka:
  bootstrap: "my-cluster-kafka-bootstrap.kafka:9092"

strimzi:
  enabled: true
cnpg:
  enabled: true
