apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: openshift-gitops
type: Opaque
stringData:
  slack-token: xoxb-REPLACE-ME
  email-username: argocd@example.com
  email-password: REPLACE
