apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prediction-api
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prediction-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    any: true
