apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      strimzi.io/name: my-cluster-kafka-exporter
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    any: true
