
name: Build Agent Image
on:
  push:
    branches: [ main ]
    paths:
      - 'agents/**'
      - 'docker/Dockerfile.agent'
      - 'requirements_agent.txt'
      - '.github/workflows/agent-ci.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.agent
          push: true
          tags: ghcr.io/${{ github.repository }}/tennis-agent:${{ github.sha }}
