name: Build & Publish Docs
on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Faster builds: pip caching keyed on requirements-docs.txt
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: docs/requirements-docs.txt

      - run: python -m pip install --upgrade pip
      - run: pip install -r docs/requirements-docs.txt

      # Optional sanity check (will fail fast if plugin missing)	

      - run: mkdocs build --strict

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

